export default [
    {
      category: "Aptitude",
      categoryid: 1,
      id: 1,
      question:
        "1.Find the sum of the factors of 3240",
      options: [
        "10890",
        "11000",
        "10800",
        "10190",
      ]
    },
    {
      category: "Aptitude",
      categoryid: 1,
      id: 2,
      question: "2.The product of 3×2 matrix and 2×3 matrix will result in what order matrix? ",
      options: [
       "3 x 2",
       "2 x 2",
       "2 x 3",
       "3 x 3",
  ]
    },
    {
      category: "Aptitude",
      categoryid: 1,
      id: 3,
      question:"3.When a die is rolled, the probability of landing with 2 is?",
      options: [
        "3/6",
        "1/6",
        "2/6",
        "5/6",
      ]
    },
    {
      category: "Aptitude",
      categoryid: 1,
      id: 4,
      question: "4.Sin (90° – x) equals? ",
      options: [
        "Sin x",
        "1 – Sin x",
        "Cos x",
       " Cosec x",
      ]
    },
    {
      category: "Aptitude",
      categoryid: 1,
      id: 5,
      question: "5.Six times a number reduced by ten equals 50. What is the number? ",
      options: ["8", "9", "10", "11"]
    },
    {
      category: "Aptitude",
      categoryid: 1,
      id: 6,
      question: "6.40% of 210 is same as one third of ?",
      options: [
        "840",
        "280 ",
        "252",
        "84",
      ]
    },
    {
      category: "Aptitude",
      categoryid: 1,
      id: 7,
      question: "7.Find the area of a triangle whose vertices are A(-2,-3), B(3,2) and C(-1,-8)",
      options: [
        "10",
        "15",
        "20",
        "25",
      ]
    },
    {
      category: "Aptitude",
      categoryid: 1,
      id: 8,
      question: "8.In a simultaneous throw of two dice, the probability of getting a total of 7 is",
      options: [" 4/6", "3/6", "2/6", "1/6"]
    },
    {
      category: "Aptitude",
      categoryid: 1,
      id: 9,
      question: "9.If half of five is three, what would a third of ten be?",
      options: ["3", "4", "5", "6"]
    },
    {
      category: "Aptitude",
      categoryid: 1,
      id: 10,
      question: "10.What is the arithmetic mean of all the multiples of two from 2 to 16 inclusive?",
      options: [
        "2",
        "7",
        "9",
        "14",
      ]
    },
    {
      category: "Aptitude",
      categoryid: 1,
      id: 11,
      question: "11.What is the area of a circle which as 6 by 8 rectangles inscribed in it?",
      options: ["64 π", "48 π", "36 π", "25 π"]
    },
    {
      category: "Aptitude",
      categoryid: 1,
      id: 12,
      question: "12.The value of log 28 is: ",
      options: ["64", "16", "4", "3"]
    },
    {
      category: "Aptitude",
      categoryid: 1,
      id: 13,
      question:
        "13.The volume of a cylinder with a radius of 3 cm and height of 4 cm is",
      options: ["36 cm3", " 75.36 cm3","113.11 cm3", " 150.72cm3"]
    },
    {
      category: "Aptitude",
      categoryid: 1,
      id: 14,
      question: "14.Anikate is 8 years older than her sister, if he is 29 years in 2013, in which year was his sister born.",
      options: ["1984", "1992", "1994", " 2005"]
    },
    {
      category: "Aptitude",
      categoryid: 1,
      id: 15,
      question: "15.In a classroom of 125 students, 75 are male students. What percent of the classroom is female? ",
      options: [ " 60%","40%","0.6%","0.4%"]
    },
    {
      category: "Aptitude",
      categoryid:1,
      id: 16,
      question: "16.Choose the number that is 1/4 of half of 1/5 of 200?  ",
      options: ["40", "20", "10", "5"]
    },
    {
      category: "Aptitude",
      categoryid:1,
      id: 17,
      question: "17.If 7 cats can catch 7 rats in 7 minutes. How many cats does it take to catch 140 rats in 140 minutes? ",
      options: [" 20 cats", " 15 cats", " 10 cats", " 7 cats"]
    },
    {
      category: "Aptitude",
      categoryid:1,
      id: 18,
      question: "18.There are 20 chickens, 4 dogs and 8 horses on a farm. How many legs are there?  ",
      options: [
        "88",
        "98",
        "78",
        "108",
      ]
    },
    {
      category: "Aptitude",
      categoryid: 1,
      id: 19,
      question: "19.Which is the greatest?    ",
      options: ["200/102 ","200/101", "200/103 ","200/104",]
    },
    {
      category: "Aptitude",
      categoryid:1,
      id: 20,
      question: "20.If the ratio of A:B is 2:7 and the ratio of B:C is 21: 6, what is the ratio of A:C ?   ",
      options: [" 1:1","2:6","7:21","1:3",]
    },
  
  {
      category: "Computer Fundamentals",
      categoryid: 2,
      id: 21,
      question:"1.A process is a _______. ",
      options: [
       "single thread of execution",
       "program in the execution",
       "program in the memory",
       "task",
      ]
    },
    {
      category: "Computer Fundamentals",
      categoryid: 2,
      id: 22,
      question: "2.What is smallest unit of the information?",
      options: [
        "A bit",
        "A byte",
        "A block",
        "A nibble",
  ]
    },
    {
      category: "Computer Fundamentals",
      categoryid: 2,
      id: 23,
      question:"3.What is the decimal equivalent of the binary number 10111?",
      options: [
        "21",
        "39",
        "42",
        "23",
      ]
    },
    {
      category: "Computer Fundamentals",
      categoryid: 2,
      id: 24,
      question: "4.How many color dots make up one color pixel on a screen?",
      options: [
      "265",
       "16",
       "8",
       "3",
      ]
    },
    {
      category: "Computer Fundamentals",
      categoryid: 2,
      id: 25,
      question: "5.Which of the following values is the correct value of this hexadecimal code 1F.01B? ",
      options: ["35.0065918","32.0065918","31.0065918","30.0065918",]
    },
    {
      category: "Computer Fundamentals",
      categoryid: 2,
      id: 26,
      question: "6.How is the data stored on the diskette?",
      options: [
        "Ink",
        "Laser bubbles ",
        "Magnetism",
        "Circuits",
      ]
    },
    {
      category: "Computer Fundamentals",
      categoryid: 2,
      id: 27,
      question: "7.Which of the following is the smallest visual element on a video monitor? ",
      options: [
        "Character",
        "Pixel",
        "Byte",
        "Bit",
      ]
    },
    {
    category: "Computer Fundamentals",
      categoryid: 2,
      id: 28,
      question: "8.Which of the following natural element is the primary element in computer chips?  ",
      options: ["Silicon", "Carbon", "Iron", "Uranium",]
    },
    {
      category: "Computer Fundamentals",
      categoryid: 2,
      id: 29,
      question: "9.Which of the following values is the correct value of this hexadecimal code ABCDEF?",
      options: ["11259375","11259379","11259312","11257593",]
    },
    {
      category: "Computer Fundamentals",
      categoryid: 2,
      id: 30,
      question: "10.Which of the following is an output device? ",
      options: ["Keyboard","Mouse","Light pen","VDU",]
    },
    {
     category: "Computer Fundamentals",
      categoryid: 2,
      id: 31,
      question: "11.Which of the following is an input device?",
      options: ["Plotter","Printer","VDU","Mouse",]
    },
    {
      category: "Computer Fundamentals",
      categoryid: 2,
      id: 32,
      question: "12.Which of the following is the extension of Notepad?",
      options: [".txt",".xls",".ppt",".bmp",]
    },
    {
      category: "Computer Fundamentals",
      categoryid: 2,
      id: 33,
      question: "13.BIOS is used?",
      options: ["By operating system", "By compiler", "By interpreter", "By application software",]
    },
    {
      category: "Computer Fundamentals",
      categoryid: 2,
      id: 34,
      question: "14.What is the mean of the Booting in the system? ",
      options: ["Restarting computer", "Install the program", "To scan", "To turn off",]
    },
    {
       category: "Computer Fundamentals",
      categoryid: 2,
      id: 35,
      question: "15.Which of the following is not one of the internal components of a CPU? ",
      options: [ " Control sequencer","M-D-R","M-A-R","Floppy disk",]
    },
    {
      category: "Computer Fundamentals",
      categoryid: 2,
      id: 36,
      question: "16.What is the speed of computer measured in? ",
      options: ["Nanoseconds", "Kilo-seconds", "Gigahertz", "Megabytes",]
    },
    {
      category: "Computer Fundamentals",
      categoryid: 2,
      id: 37,
      question: "17.Which of the following shortcut key shows the properties of a file? ",
      options: ["Alt + Ctrl","Alt + P", "Alt + F3", "Alt + Enter",]
    },
    {
      category: "Computer Fundamentals",
      categoryid: 2,
      id:38,
      question: "18.Which of the following processor has a fixed length of instructions? ",
      options: [ "Main processor","COM","Dual Core","RISC",]
    },
    {
      category: "Computer Fundamentals",
      categoryid: 2,
      id: 39,
      question: "19.Which is the greatest?    ",
      options: ["Download the file via the internet", "To connect with other devices", "To reduce the internet speed", "None of the these",]
    },
    {
      category: "Computer Fundamentals",
      categoryid: 2,
      id: 40,
      question: "20.Which of the following memory cannot be directly accessed?  ",
      options: ["Primary memory","Secondary memory","RAM","DRAM",]
  },
  {
      category: "Geography",
      categoryid:3,
      id: 41,
      question:"1.India shares land borders with how many countries? ",
      options: ["Six","Seven","Eight","Nine",]
  },
  {
    category: "Geography",
    categoryid:3,
    id: 42,
    question: "2.Which among the following state produces maximum raw silk in India?",                                             
    options: [ "Bihar",
      "Assam",
      "West Bengal",
      "Karnataka",]
  },
  {
    category: "Geography",
    categoryid:3,
    id: 43,
    question: "3.The Coonoor hill station is located in which one of the following states of India? ",                          
    options: ["Karnataka",
  " Kerala",
  "Tamil Nadu",
   "Andhra Pradesh",]
  },
  {
    category: "Geography",
    categoryid:3,
    id:44,
    question:"4.The lacustrine deposits of Kashmir called ‘Karewas’ are known for ",                                                                  
    options: ["Saffron Cultivation",
  "Terrace farming",
  "Apple Orchards",
  "Jhum Cultivation",
]
},
  {
    category: "Geography",
    categoryid:3,
    id:45,
    question:"5.Which of the following hill stations is considered as the Ooty of Andhra Pradesh?",                                                      
    options: ["Sri Sailam","Araku Valley","Lambasingi","Papi Hills",]},
  {
    category: "Geography",
    categoryid:3,
    id:46,
    question:"6.Which of the following types of Iron ores is mined at Bailadila ? ",                                                                                            
    options: [" Haematite","Magnetite","Limonite","None of the above",]},
  {
    category: "Geography",
    categoryid:3,
    id:47,
    question:"7.Which of the following is the largest oil field in India?",                                                                           
    options: ["Bombay High Oilfield","Ankleswar Oilfield","Naharkatia Oilfiels","Digboy Oilfield",]},
  {
    category: "Geography",
    categoryid:3,
    id:48,
    question:"8.Green Revolution was introduced in the 20th Century during the decade of which of the following? ",                                       
    options: ["Fourties","Fifties","Sixties","Seventies",]},
  {
    category: "Geography",
    categoryid:3,
    id:49,
    question:"9.Jhooming is practised by which of the following tribal group?",                                                                                                
    options: ["The Todas","The Santhals","The Khasis","The Bhotias",]},
  {
    category: "Geography",
    categoryid:3,
    id:50,
    question:"10.Which of the following is an example of ‘Parallel Cropping’?",                                                                          
    options: ["Wheat + Mustard","Cotton + Wheat","Sorghum + Potato","Potato + Rice",
  ]},
  {
    category: "Geography",
    categoryid:3,
    id:51,
    question:"11.Which of the following is the main sources of irrigation in India? ",                                                                    
    options: ["Tank","Canal","Wells & Tubewells","None of the above",
  ]},
  {
    category: "Geography",
    categoryid:3,
    id:52,
    question:"12.Which of the following is a tidal port? ",                                                                                 
    options: [ "Vishakapatnam","Kandla","Tuticorin","Chennai",]},
  {
    category: "Geography",
    categoryid:3,
    id:53,
    question:"13.Which of the following crops is an example of Kharif Crops?  ",                                                          
    options: ["Gram","Cotton","Pea","Wheat" ,]},
  {
    category: "Geography",
    categoryid:3,
    id:54,
    question:"14.Which state is not a part of the 'Seven Sisters' of North East? " ,                                                      
    options: ["Meghalaya","Sikkim","Arunachal Pradesh","Tripura",]},
  {
    category: "Geography",
    categoryid:3,
    id:55,
    question:"15.River Sutlej enters India through which pass?",                                                                   
    options:["Zoji la ","Nathula","Lipulekh","Shipki la",]
  },
  {
    category: "Geography",
    categoryid:3,
    id:56,
    question:"16.Which of the following dams is located in Karnataka?",                                                                
    options: ["Tungabhadra Dam","Gandhi Sagar Dam","Srisailam Dam","Mullaiperiyar Dam",]
},
  {
   category: "Geography",
   categoryid:3,
   id:57,
  question:"17. Which among these is a form of precipitation? ",                                                         
   options: ["Dew","Fog","Mist","Hail",]},
  {
  category: "Geography",
  categoryid:3,
  id:58,
  question:"18. The topical rainforests in the Amazon basin is known as ",                                                                      
  options: ["Savanna",
  "Prairies",
  "Selvas",
  "Pampas",]},
  {
  category: "Geography",
  categoryid:3,
  id:59,
  question:"19. Which is the smallest Country (in population)?",                                                     
  options: ["Vatican city",
  "Nauru",
  "Monaco",
  "Palau",]},
  {
  category: "Geography",
  categoryid:3,
  id:60,
  question:"20.Which is called 'the land of thousand lakes'.", 
  options: ["Switzerland",
  "Canada",
  "Finland",
  "Sweden",]},
  {
  category: "History",
  categoryid:4,
  id: 61,
  question:"1.Under Akbar, the Mir Bakshi was required to look after ",
  options: ["military affairs","the state treasury","the royal household","the land revenue system",]
  },
  {
  category: "History",
  categoryid:4,
  id: 62,
  question: "2.Tripitakas are sacred books of ?",
  options: [ "Buddhists",
  "Hindus",
  "Jains",
  "None of the above",]
  },
  {
  category: "History",
  categoryid:4,
  id: 63,
  question: "3.The system of competitive examination for civil service was accepted in principle in the year  ",                          
  options: ["1833",
  "1853",
  "1858",
  "1882",]},
  {
  category: "History",
  categoryid:4,
  id:64,
  question:"4.The Vijayanagara ruler, Kirshnadev Raya's work Amuktamalyada, was in   ", 
  options: ["Telugu",
  "Sanskrit",
  "Tamil",
  "Kannada",]},
  {
  category: "History",
  categoryid:4,
  id:65,
  question:"5.Todar Mal was associated with ",
  options: ["music",
  "literature",
  "finance",
  "law",]},
  {
  category: "History",
  categoryid:4,
  id:66,
  question:"6.Sardar Vallabhbhai Patel was equated with ", 
  options: ["Mazzini",
  "Cavour",
  "Garibaldi",
  "Bismarck",]},
  {
  category: "History",
  categoryid:4,
  id:67,
  question:"7.Who was the first Governor General of  the new Indian Dominion? ",                                                                           
  options: ["Rajendra Prasad",
  "Vallabhbhai Patel",
  "Rajagopalachari",
  "Lord Mountbatten",]},
  {
  category: "History",
  categoryid:4,
  id:68,
  question:"8.Gandhi-Irwin Pact was signed on ", 
  options: ["March 10, 1930",
  "March 20, 1931",
  "March 20,1932",
  "March 5,1931",]},
  {
  category: "History",
  categoryid:4,
  id:69,
  question:"9.The weekly Commonweal was founded by",    
  options: ["Annie Besant",
  "Bipan Chandra Pal",
  "Bal Gangadhar Tilak",
  "Sarojini Naidu",]},
  {
  category: "History",
  categoryid:4,
  id:70,
  question:"10.The first plans for an Indian railway system was made by",                                                                          
  options: ["Minto",
  "Amherst",
  "Hardinge",
  "Cornwallis",]},
  {
  category: "History",
  categoryid:4,
  id:71,
  question:"11.The Kalinga was fought in ",
  options: ["321 BC",
  "301 BC",
  "261 BC",
  "241 BC",]},
  {
  category: "History",
  categoryid:4,
  id:12,
  question:"12.We can know about early vedic period from ",
  options: [ "archaeological excavations",
  "the Rig Veda",
  "Jatak Katha",
  "contemporary culture",]},
  {
  category: "History",
  categoryid:4,
  id:73,
  question:"13.The Upanishads are ",                                                  
  options: ["a source of Hindu philosophy",
  "books of ancient Hindu laws",
  "books on social behavior of man",
  "prayers to God",]},
  {
  category: "History",
  categoryid:4,
  id:74,
  question:"14.Ustad Mansur was a famous painter in the reign of " , 
  options: ["Shajahan",
  "Akbar",
  "Humayun",
  "Jahangir",]},
  {
  category: "History",
  categoryid:4,
    id:75,
  question:"15.Which of the following treaties ended World War II?", 
  options: [ "Peace treaties",
   "Geneva Conference",
  "Treaty of Versailles",
   "None of these",
  ]},
  {
  category: "History",
  categoryid:4,
  id:76,
  question:"16.Wall Street collapse led to:",
  options: [ "World War II",
   "Recession",
   "U.S. attack on Iraq",
   "Great Depression",]},
  {
  category: "History",
  categoryid:4,
  id:77,
  question:"17.Opium wars were fought between the British and",
  options: [ "China",
   "Bhutan",
   "Myanmar (Burma)",
  "Afghanistan",]},
  {
  category: "History",
  categoryid:4,
  id:78,
  question:"18. Who advocated Nazism in Germany? ",  
  options: [ "Fedrick William IV",
   "Adolf Hitler",
   "Bismark",
  "William III",]},
  {
  category: "History",
  categoryid:4,
  id:79,
  question:"19.What does the “T” stands for in NATO?",
  options: [ "Troops",
   "Trustee",
   "Treaty",
   "Training",]},
  {
  category: "History",
  categoryid:4,
  id:80,
  question:"20.Which of the following is the oldest civilization of the world?",                                              
  options: ["Indus Valley Civilization",
   "Mesopotamian Civilization",
   "Nile Valley Civilization",
   "Chinese Civilization",]},
  {
  
  category: "Reasoning",
  categoryid:5,
  id: 81,
  question:"1.If NOIDA is written as OPJEB, then what will be the code for DELHI? ",
  options: ["EFMAK","EFAMK","EFMIJ","EFMIK",],
  },
  {
  category: "Reasoning",
  categoryid:5,
  id: 82,
  question: "2.If AIRLINE is written as ENILRIA7, then RAILWAY will be written as",
  options: [ "YAWLIAR7",
  "YAWLIAR8",
  "YAWILAR7",
  "YAWILAR8",],
  },
  {
  category: "Reasoning",
  categoryid:5,
  id: 83,
  question: "3.If CAT is coded as PATC, JOY is coded as POYJ; similarly the word WING will be coded as ",                          
  options: ["PIGNW",
  "PINGW",
  "PGNIW",
  "PIWGN",]},
  {
  category: "Reasoning",
  categoryid:5,
  id:84,
  question:"4.Which number should come next in the series 1, 2, 3, 10, ___  ",  
  options: ["79",
  "99",
  "89",
  "98",]},
  {
  category: "Reasoning",
  categoryid:5,
  id:85,
  question:"5.Which number is wrong in the series 2, 6, 15, 31, 56, 93?",  
  options: ["6",
  "31",
  "56",
  "93",]},
  {
  category: "Reasoning",
  categoryid:5,
  id:86,
  question:"6.The number comes next in the series 12, 36, 109, 329, ...   ", 
   options: ["900",
  "990",
  "890",
  "None of the above",]},
  {
  category: "Reasoning",
  categoryid:5,
  id:87,
  question:"7.Suppose a series is 6, 11, 21, 36, 56, ? the number comes at the place of question mark in the given series is ",
  options: ["91",
  "21",
  "52",
  "81",]},
  {
  category: "Reasoning",
  categoryid:5,
  id:88,
  question:"8.Suppose a series is 1, 9, 25, 49, ?, 121, the number comes at the place of question mark in the given series is  3", 
  options: ["91",
  "21",
  "52",
  "81",]},
  {
  category: "Reasoning",
  categoryid:5,
  id:89,
  question:"9.The number comes after the series 8, 28, 116, 584, ... ",  
  options: ["3504",
  "3507",
  "3508",
  "3509",]},
  {
  category: "Reasoning",
  categoryid:5,
  id:90,
  question:"10.What will be the next number in the series 13, 17, 19, 23, 29,...?", 
  options: ["31",
  "33",
  "35",
  "37",]},
  {
  category: "Reasoning",
  categoryid:5,
  id:91,
  question:"11.What will be the missing number in the series 196, 169, 144, __, 100, 81?     ",
   options: ["121",
  "120",
  "119",
  "118",]},
  {
  category: "Reasoning",
  categoryid:5,
  id:92,
  question:"12.Which number comes next in the series 1536, 384, 96, ___? ", 
  options: [ "23",
  "24",
  "28",
  "18",]},
  {
  category: "Reasoning",
  categoryid:5,
  id:93,
  question:"13.If PINK is coded as 1691411, then RED will be coded as",                                                  
  options: ["1963",
  "1854",
  "1853",
  "1954",]},
  {
  category: "Reasoning",
  categoryid:5,
  id:94,
  question:"14.Which of the following is the odd one from the given alternatives?",  
   options: ["Driving",
  "Diving",
  "Swimming",
  "Sailing",]},
  {
  category: "Reasoning",
  categoryid:5,
  id:95,
  question:"15.Which of the following is the odd number from the given alternatives?",  
  options: [ "1090",
   "962",
  "626",
   "841",
  ]},
  {
  category: "Reasoning",
  categoryid:5,
  id:96,
  question:"16.A factory always has",   
   options: [ "Files",
   "Workers",
   "Air conditioners",
   "Chimneys",]},
  {
  category: "Reasoning",
  categoryid:5,
  id:97,
  question:"17.What will be the missing letters in the series EQ, FS, HW, KA, __, TL?  ",  
  options: [ "AL", "OF","HP","None of the above",]},
  {
  category: "Reasoning",
  categoryid:5,
  id:98,
  question:"18.Which of the following is different from others?", 
  options: [ "Barber",
   "Blacksmith",
   "Tailor",
  "Carpenter",]},
  {
  category: "Reasoning",
  categoryid:5,
  id:99,
  question:"19.Which of the following pairs of words are differently related? ", 
  options: [ "Kind : Cruel",
   "Slow : Sluggish",
   "Stale : Fresh",
   "Truth : Lie",]},
  {
  category: "Reasoning",
  categoryid:5,
  id:100,
  question:"20.A thermometer is to temperature as a compass is to",                                              
  options: ["Needle",
   "Pressure",
   "Direction",
   "None of the above",]},
  {
  category: "Science&Technology",
  categoryid:6,
  id:101,
  question:"1.What is Ceres, that was referred to in a recent study by the NASA?",         
  options: ["Asteroid",
   "Dwarf Planet",
   " Black hole",
   " Comet",]},
  {
  category: "Science&Technology",
  categoryid:6,
  id:102,
 question:"2.Which is the first country, where WhatsApp is launching its ‘WhatsApp Pay’?",         
  options: [
   " India",
   " Brazil",
   " Japan",
   "South Korea",]},
  {
  category: "Science&Technology",
  categoryid:6,
  id: 103,
  question: "3.What is L.vannamei, a species that was seen in news recently? ",                          
  options: ["Frog",
  "Turtle",
  "Shrimp",
  " Prawn",]},
  {
  category: "Science&Technology",
  categoryid:6,
  id:104,
  question:"4.Which social media giant launched a new tool Business Suite to help small businesses?",  
  options: [ "Twitter",
   "Facebook",
   "TikTok",
  "We Chat",]},
  {
  category: "Science&Technology",
  categoryid:6,
  id:105,
  question:"5.Pioneers is a programme of which country's space agency?",      
  options: ["India",
  "UK",
   "USA",
  "Germany",]},
  {
  category: "Science&Technology",
  categoryid:6,
  id:106,
  question:"6.The Ministry of Electronics and IT has asked which company to withdraw its privacy policy?",     
  options: [ "Google",
   "WhatsApp",
  "Microsoft",
  "Amazon",]},
  {
  category: "Science&Technology",
  categoryid:6,
  id:107,
  question:"7.'ISIpedia', the online portal, is associated with which field? ", 
  options: ["Health",
  "Climate Change",
   "Religion",
   "Sports",]},
  {
  category: "Science&Technology",
  categoryid:6,
  id:108,
  question:"8.CSS, a new software released by the Union Health Ministry, stands for?", 
  options: [ "Coronavirus Science Software",
   "Covid Severity Score",
   "Covid Serious Score",
   "Covid Scientific Score",]},
  {
  category: "Science&Technology",
  categoryid:6,
  id:109,
  question:"9.Cambridge-1, which was making news recently, is the supercomputer of which country?",
  options: ["UK",
   "Russia",
  "USA",
  " Japan",]},
  {
  category: "Science&Technology",
  categoryid:6,
  id:110,
  question:"10.Which IT consulting company has been engaged by Coal India Ltd, for ", 
  options: ["Digitalisation of mines?",                                       
  "Accenture",
  " Tata Consultancy Services",
  "Wipro",
  "Infosys",]},
  {
  category: "Science&Technology",
  categoryid:6,
  id:111,
  question:"11.Jezero is a Crater located in which planet? ",
  options: ["Mercury",
   "Venus",
   "Mars",
   "Jupiter",]},
  {
  category: "Science&Technology",
  categoryid:6,
  id:112,
  question:"12.Lucy Mission, which was seen in the news recently, is associated with which space agency? ",
    options: [ " ISRO",
  "NASA",
  " Blue Origin",
  " SpaceX",]},
  {
  category: "Science&Technology",
  categoryid:6,
  id:113,
  question:"13.Deep Space Atomic Clock, which was seen in the news recently, is associated with which space agency?", 
  options: [" ISRO",
  "NASA",
  "Virgin Galactic",
  " SpaceX",]},
  {
  category: "Science&Technology",
  categoryid:6,
  id:114,
  question:"14.Which space agency is set to launch the ‘Laser Communications Relay Demonstration (LCRD)’?  " ,
   options: [" ISRO",
  "NASA",
  "ESA",
  "SpaceX",]},
  {
  category: "Science&Technology",
  categoryid:6,
  id:115,
  question:"15.‘Imaging X-ray Polarimetry Explorer (IXPE) mission’ is a collaboration between NASA and which country?", 
   options: [ "India",
   " Japan",
  " Italy",
   "Germany",
  ]},
  {
  category: "Science&Technology",
  categoryid:6,
  id:116,
  question:"16.What is the name of the recently discovered group of planets, which do not orbit a star?",  
  options: [ "Exo-planets",
   " Rogue Planets",
   " Mystery Planets",
   " Floating Planets",]},
  {
  category: "Science&Technology",
  categoryid:6,
  id:117,
  question:"17.Which company launched new Artificial Intelligence chips called 'Gaudi2' and 'Greco'?",
   options: [
   "Nvidia",
  "Intel",
   "Qualcomm",
  "Samsung",]},
  {
  category: "Science&Technology",
  categoryid:6,
  id:118,
  question:"18.Europa Clipper spacecraft’ is a flagship project of which space agency? ",  options: [ "NASA",
   "ESA",
   "ISRO",
  "JAXA",]},
  {
  category: "Science&Technology",
  categoryid:6,
  id:119,
  question:"19.Which institution launched the peta-scale supercomputer ‘PARAM Shakti’? ",
  options: [ "IISc Bengaluru",
   "IIT Kharagpur",
   "IIT Madras",
   "NIT Warangal",]},
  {
  category: "Science&Technology",
  categoryid:6,
  id:120,
  question:"20.Scientists from which country has developed a new technology to filter micro-plastics from water?  ", 
   options: [" India",
   "South Korea",
   "Australia",
   "UAE",]},
  {
  category: "Sports",
  categoryid:7,
  id:121,
  question:"1.Which was the 1st non Test playing country to beat India in an international match?",         
  options: ["Canada",
  "Sri Lanka",
  "Zimbabwe",
  "East Africa",]},
  {
  category: "Sports",
  categoryid:7,
  id:122,
  question:"2.India won its first Olympic hockey gold in...? ",
  options: [
  "1928",
  "1932",
  "1936",
  "1948",]},
  {
  category: "Sports",
  categoryid:7,
  id: 123,
  question: "3.Which cricketer has scored the maximum runs in ODIs? ",                          
  options: ["Kapil Dev",
  "Sunil Gavaskar",
   "Sachin Tendulkar",
  "Virat Kohli",]},
  {
  category: "Sports",
  categoryid:7,
  id:124,
  question: "4.Epsom (England) is the place associated with",
  options:['Horse racing',   'Polo','Shooting','Snooker',]},
  {
  category: "Sports",
  categoryid:7,
  id:125,
  question:"5.What is the mascot of the 2022 Asian Games? ",
  options: ["Barame, Chumuro, Vichuon","Congcong, Lianlian, Chenchen","Poppo and Cuccu","Pan Pan",]},
  {
  category: "Sports",
  categoryid:7,
  id:126,
  question:"6.Which sport's professional league tournament is “Liiga”?", 
  options: ["Football",
  "Ice Hockey",
  "Baseball",
   "Field Hockey",]},
  {
  category: "Sports",
  categoryid:7,
  id:127,
  question:"7.Which sport’s competition is known as “Indian Wells Masters”?", 
  options: ["Football",
  "Volleyball",
  "Tennis",
  "Polo",]},
  {
  category: "Sports",
  categoryid:7,
  id:128,
  question:"8.Which Indian chess player recently won the Cairns Cup chess tournament? ",   
  options: [ "Koneru Humpy",
  "Viswanathan Anand",
  "Harikrishna P",
   "Adhiban",]},
  {
  category: "Sports",
  categoryid:7,
  id:129,
  question:"9.Which country won the Uber Cup title in 2022? ",  options: ["India",
  "Indonesia",
  "South Korea",
  "China",]},
  {
  category: "Sports",
  categoryid:7,
  id:130,
  question:"10.What is the mascot of the Fourth Khelo India Youth Games 2022?  ",
  options: ["Appu",                                       
  "Dhakad",
  " Veer",
  "Ghambhir",]},
  {
  category: "Sports",
  categoryid:7,
   id:131,
   question:"11.Which sports body of India has been suspended by the global apex body for ‘undue influence from third parties’? ",
   options: ["Football",
   "Tennis",
   " Badminton",
   " Athletics",]},
  {
  category: "Sports",
  categoryid:7,
  id:132,
  question:"12.Which country played host to the ‘Asia Cup 2022’? ", 
   options: [ " India",
  " Sri Lanka",
  " UAE",
  " Bangladesh",]},
  {
  category: "Sports",
  categoryid:7,
  id:133,
  question:"13.Who is the first Indian to win four medals at World Wrestling Championships?", 
   options: [" Vinesh Phogat",
  " Bajrang Punia",
  " Babita kumari",
  "  Gita Phogat",]},
  {
   category: "Sports",
   categoryid:7,
   id:134,
   question:"14.Which team won the 36th National Games of India, held in 2022?" ,
   options: ["Railways Team",
   "Services Team",
  "Maharashtra State",
   "Haryana State",]},
  {
  category: "Sports",
  categoryid:7,
  id:135,
  question:"15.Which racing driver won the US Grand Prix Title in 2022?",
   options: [  "Sebastian Vettel",
   "Charles Leclerc",
   "Max Verstappen",
  "Lewis Hamilton",
  ]},
  {
  category: "Sports",
  categoryid:7,
  id:136,
  question:"16.Which state hosted the 2nd edition of North East Olympic Games in 2022?", 
  options: ["Assam",
   "Meghalaya",
   "Manipur",
  "Sikkim",]},
  {
  category: "Sports",
  categoryid:7,
  id:137,
  question:"17.Which company became the official partner of FIH Odisha Hockey Men’s World Cup 2023?", 
  options: ["Byju's",
  "Tata Steel",
  "Reliance Industries",
  "Jio",]},
  {
   category: "Sports",
   categoryid:7,
   id:138,
   question:"18.Which footballer created a record as the professional football player with the most appearances in FIFA World Cup?  ", 
   options: [ "Cristiano Ronaldo",
   "Lionel Messi",
  "Eiji Kawashima",
   "Alfredo Talavera",]},
  {
  category: "Sports",
      categoryid:7,
    id:139,
  question:"19.Satwiksairaj Rankireddy and Chirag Shetty, play which sports?", 
  options: ["Archery",
  "Table Tennis",
  "Badminton",
  "Shooting",]},
  {
  category: "Sports",
      categoryid:7,
    id:140,
  question:"20.Which country claimed the inaugural U-19 women’s World Cup title?",   
  options: ["  England",
   "South Africa",
   "India",
   "Australia",]
  }
  ];
  
  export const answers = [
    { id: 1, answer: 0 },
    { id: 2, answer: 3},
    { id: 3, answer: 1 },
    { id: 4, answer: 2 },
    { id: 5, answer: 2 },
    { id: 6, answer: 2 },
    { id: 7, answer: 1 },
    { id: 8, answer: 3 },
    { id: 9, answer: 1 },
    { id:10, answer: 2 },
    { id: 11, answer: 3},
    { id: 12, answer: 3},
    { id: 13, answer:2 },
    { id: 14, answer: 3 },
    { id: 15, answer: 1 },
    { id: 16, answer: 3 },
    { id: 17, answer:3 },
    { id: 18, answer: 1},
    { id: 19, answer: 1 },
    { id:20, answer: 0 },
    { id: 21, answer: 1 },
    { id: 22, answer: 0 },
    { id: 23, answer: 3 },
    { id: 24, answer: 3 },
    { id: 25, answer: 3 },
    { id: 26, answer:2 },
    { id: 27, answer: 1 },
    { id: 28, answer: 0 },
    { id: 29, answer:2 },
    { id: 30, answer: 3 },
    { id: 31, answer: 3 },
    { id: 32, answer: 0 },
    { id: 33, answer: 0 },
    { id: 34, answer: 0 },
    { id: 35, answer: 3 },
    { id: 36, answer: 2 },
    { id: 37, answer: 3 },
    { id: 38, answer: 3},
    { id: 39, answer: 1 },
    { id: 40, answer: 1 },
    { id: 41, answer: 1 },
    { id: 42, answer: 3 },
    { id: 43, answer: 2 },
    { id: 44, answer: 0 },
    { id: 45, answer: 1 },
    { id: 46, answer: 0 },
    { id: 47, answer: 0 },
    { id: 48, answer: 2 },
    { id: 49, answer: 2 },
    { id: 50, answer: 0 },
    { id: 51, answer: 2 },
    { id: 52, answer: 1 },
    { id: 53, answer: 1 },
    { id: 54, answer: 1 },
    { id: 55, answer: 3 },
    { id: 56, answer: 0 },
    { id:57, answer: 3 },
    { id: 58, answer:2 },
    { id: 59, answer: 0 },
    { id: 60, answer: 2 },
    { id: 61, answer: 0 },
    { id: 62, answer: 0 },
    { id: 63, answer: 1 },
    { id: 64, answer: 0 },
    { id: 65, answer: 2 },
    { id: 66, answer: 3 },
    { id: 67, answer: 3 },
    { id: 68, answer: 3 },
    { id: 69, answer: 0 },
    { id: 70, answer: 2 },
    { id: 71, answer: 2 },
    { id: 72, answer: 1 },
    { id: 73, answer: 0 },
    { id: 74, answer: 3},
    { id: 75, answer:0 },
    { id: 76, answer: 3 },
    { id: 77, answer: 0 },
    { id: 78, answer: 1 },
    { id: 79, answer: 2 },
    { id: 80, answer: 1 },
    { id: 81, answer: 2 },
    { id: 82, answer: 0 },
    { id: 83, answer: 1 },
    { id: 84, answer: 1 },
    { id: 85, answer: 3 },
    { id: 86, answer: 1 },
    { id: 87, answer: 3 },
    { id:88, answer: 3},
    { id: 89, answer: 2 },
    { id: 90, answer: 0 },
    { id: 91, answer: 0 },
    { id: 92, answer: 1 },
    { id: 93, answer: 1 },
    { id: 94, answer:0 },
    { id: 95, answer: 1 },
    { id: 96, answer: 1 },
    { id: 97, answer: 1 },
    { id: 98, answer: 0 },
    { id: 99, answer: 1 },
    { id: 100, answer: 2 },
    { id: 101, answer: 1 },
    { id: 102, answer: 1 },
    { id: 103, answer: 2 },
    { id: 104, answer: 1 },
    { id: 105, answer: 2 },
    { id: 106, answer: 1 },
    { id: 107, answer: 1 },
    { id: 108, answer: 1 },
    { id: 109, answer: 0 },
    { id: 110, answer: 0 },
    { id: 111, answer: 2 },
    { id: 112, answer: 1 },
    { id: 113, answer: 1 },
    { id:114, answer: 1 },
    { id: 115, answer: 2 },
    { id: 116, answer: 1 },
    { id: 117, answer: 1 },
    { id: 118, answer: 0 },
    { id: 119, answer: 1 },
    { id: 120, answer: 1 },
    { id: 121, answer: 1 },
    { id: 122, answer: 0 },
    { id: 123, answer: 2 },
    { id: 124, answer: 0 },
    { id: 125, answer: 1 },
    { id: 126, answer: 1 },
    { id: 127, answer: 2 },
    { id: 128, answer: 0 },
    { id: 129, answer: 2 },
    { id: 130, answer: 1 },
    { id: 131, answer: 0 },
    { id: 132, answer: 2 },
    { id: 133, answer: 1 },
    { id: 134, answer: 1 },
    { id: 135, answer: 2 },
    { id: 136, answer: 1 },
    { id: 137, answer: 1 },
    { id: 138, answer: 1 },
    { id: 139, answer: 2 },
    { id: 140, answer: 2 },
  ];
  
  export const categories = [
    {
      category: "Aptitude",
      categoryid: 1,
    },
    {
      category: "Computer Fundamentals",
      categoryid: 2,
    },
    {
      category: "Geography",
      categoryid: 3,
    },
    {
      category: "History",
      categoryid: 4,
    },
    {
      category: "Reasoning",
      categoryid: 5,
    },
    {
      category: "Science&Technology",
      categoryid: 6,
    },
    {
      categoryid: 7,
      category: "Sports",
    },
  ];
